language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules
    
stages:
- install
- build
- name: release
  if: tag IS present    

jobs:
  include:
  - stage: install
    script:
    - "yarn install"
  - stage: build
    script:
    - "yarn build"
  - stage: release
    script:
    - "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin"
    - docker build -t testra .
    - docker tag testra testra/testra-web
    - docker push testra/testra-web
