language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules
    
branches:
  only:
  - master

script:
  - yarn install
  - yarn build
  - "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin"
  - docker build -t testra .
  - docker tag testra testra/testra
  - docker push testra/testra
